### ISSUE TITLE
UWP fonts 

### ISSUE THREAD

**Issue by alllohaaa** [jsmarcus/Xamarin.Plugins#13]
Can't get fonts on UWP, at least FontAwesome and Ionicons. Probably you should follow this advise http://stackoverflow.com/a/35476577/2987062  and check "Generate library layout" option in the Build configuration

**Comment by nbrowne** [comment]
@alllohaaa I think you're onto something. I was able to get the fonts (material design specifically) working in UWP by making sure that ```Plugin.Iconize.Material.UWP\Assets\Fonts\iconize-material.ttf``` existed in the AppX output folder. I accomplished that by:

1. Creating the folder structure in the root of my UWP project ```Plugin.Iconize.Material.UWP\Assets\Fonts\```
2. Copying iconize-material.ttf to the new Fonts directory
3. Including the .ttf file in the project and setting it to "Copy if newer"
4. Rebuilding and then deploying the project

This isn't really a good solution long term, but I'm not familiar enough with nuget or xamarin to put a pull request together.

**Comment by jsmarcus** [comment]
I have modified the UWP projects to Generate library layout and updated the nugets. Try the new version, hopefully that has solved your issue. UWP is still in beta but the label and buttons should be working for you.

**Comment by alllohaaa** [comment]
Maybe I go wrong, but I guess now you have to include assets folder into nuget fonts packages somehow. I have 

> C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.NetNative.targets(396,7): error MSB3030: Could not copy the file "...\packages\Xam.Plugin.Iconize.FontAwesome\1.0.9\lib\UAP10\Plugin.Iconize.FontAwesome.UWP\Assets\Fonts\iconize-fontawesome.ttf" because it was not found.
> C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.NetNative.targets(396,7): error MSB3030: Could not copy the file "...\packages\Xam.Plugin.Iconize.Ionicons\1.0.9\lib\UAP10\Plugin.Iconize.Ionicons.UWP\Assets\Fonts\iconize-ionicons.ttf" because it was not found.

Just try your own samples in another solution and reference all dependencies through nuget

**Comment by werddomain** [comment]
i have a similar isue, but the path are different.
Each font package missing fonts ..
Tha asked path is "C:\Users\Benoit\.nuget\packages\Xam.Plugin.Iconize.SimpleLineIcons\1.0.10\lib\UAP10\Plugin.Iconize.SimpleLineIcons.UWP\Assets\Fonts\iconize-simplelineicons.ttf"

i have copied files in the right dirrectory (i had to create directory structure) and now it work

**Comment by JohBa** [comment]
I have the same problem as @alllohaaa, copying the file in the folder works, but isn't really a good workaround.

**Comment by BenDevelopment** [comment]
I'm still facing the same problem wih the last nuget version.

**Comment by tempkesss** [comment]
@werddomain me too

**Comment by miggat** [comment]
Me too

**Comment by shorlick** [comment]
Same.

**Comment by bricegomis** [comment]
I still have the same issue with the last nuget version.

**Comment by NoleHealth** [comment]
I still have the same issue with the last nuget version.

**Comment by ErikGranse** [comment]
Also having this problem with the current version of NuGet

**Comment by DevEddy** [comment]
Same thing here

**Comment by f4bo** [comment]
I'm in the same boat: 1.0.10 release and still no fixes in view...
BTW I found a dirty fix:
- go [here](https://github.com/jsmarcus/Xamarin.Plugins) and download the zip package
- put the file **iconize-fontawesome.ttf** you'll find inside, in this folder:
`C:\Users\[your username]\.nuget\packages\xam.plugin.iconize.fontawesome\1.0.10\lib\UAP10\Plugin.Iconize.FontAwesome.UWP\Assets\Fonts\`

**Comment by pcdus** [comment]
I encounter the same error for the **IconToolbarItem**: but my UWP project is **.Net Standard** type, and I use the latest version of the package (v.2.0.0.37-beta).

@f4bo  I tried to adapt your solution to my case:
- I've found the **iconize-material.ttf** if the zip package you mentioned
- I've seen that the font is already present in this folder:

> C:\Users\[my_name]\.nuget\packages\xam.plugin.iconize.material\2.0.0.37-beta\lib\uap10.0\Plugin.Iconize.Material

- but I've copied it in the following folder to match to your solution:

> C:\Users\[my_name]\.nuget\packages\xam.plugin.iconize.material\2.0.0.37-beta\lib\uap10.0\Plugin.Iconize.Material\Assets\Fonts

**_=> I've rebuild the projet, but nothing changed: the icon is still not displayed in the NavigationBar..._**

I also tried the solution given by @nbrowne:
- I've created this folder structure in the root of the UWP project:

> Plugin.Iconize.Material.UWP\Assets\Fonts\

- I've copied the **iconize-material.ttf** to the new Fonts directory
- I've included the **.ttf** file to the project and setted it to "Copy if newer"

**_=> I've rebuilt and then deployed the project but the result is still the same..._**

Do you have other suggestions?

**Comment by pcdus** [comment]
After having added an **IconLabel**, I've seen that the icon is well displayed.
So, it seems that the problem comes from the **IconToolbarItem**.
But in the samples, this IconToolBar works well...

**Comment by pcdus** [comment]
After investigation this problem only occurs when we use an IconNavigationPage as Detail of a MasterDetailPage.
I've opened the related [issue](https://github.com/jsmarcus/Xamarin.Plugins/issues/102).
